


name: draw_my_signature
description: "A Flutter package providing a customizable signature pad widget to draw and save signatures as PNG images."
version: 1.0.0
homepage: https://github.com/mdsakibulhasansanto/draw_my_signature
repository: https://github.com/mdsakibulhasansanto/draw_my_signature
issue_tracker: https://github.com/mdsakibulhasansanto/draw_my_signature/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# No assets or fonts for now
